rng_seed: 1234
temp_dir: './test_results'
levels_dir: './my_levels'
dungeon:
  max_enemies_per_encounter: 4
  max_traps_per_encounter: 1
  max_treasures_per_encounter: 1
  corridor_min_length: 2
  corridor_max_length: 4
  min_hp: 1
  max_hp: 30
  min_dodge: 0.01
  max_dodge: 0.99
  min_prot: 0.01
  max_prot: 0.99
  min_spd: 1
  max_spd: 10
ui:
  entity_scale: 0.35
  minimap_room_scale: 0.25
  minimap_corridor_scale: 0.15
  minimap_zoom_step: 0.5
  selected_color: '#ffbf00'
  unselected_color: '#b38600'
llm:
  system_prompt: "./assets/system_prompt"
  model_name: "gpt-3.5-turbo-0125"
  temperature: 0.2
  top_p: 0.1
room:
  mask: './assets/controlnet_masks/room_mask.png'
  prompt: "ddstyle, a (side view)+++ of a room set in {room_name}, {room_description}, best quality"
  negative_prompt: "top-down, (logo)++, (creature)++, (people)++, (animal)++, (face)++, ugly, badly drawn, worst quality, frame, glare, solar flare, text, monochromatic, duplication, repetition"
  inference_steps: 20
  guidance_scale: 5.0
  height: 512
  width: 1024
  save_dir: './test_results/'
entity:
  enemy_prompt: "darkest dungeon, (full body)+++ {entity_name}: ({entity_description})++, set in {place_name}: {place_description}, masterpiece++, highly detailed+, (flat empty background)+++"
  negative_enemy_prompt: "(close-up)+++, out of shot, (multiple characters)++, (many characters)++, not centered, floor, walls, pedestal, duplication, repetition, bad anatomy, monochromatic, disfigured, badly drawn, bad hands, naked, nude"
  obj_prompt: "darkest dungeon, (empty flat background)+++, {entity_name}: {entity_description}, in {place_name}: {place_description}"
  negative_obj_prompt: "(close-up)+++, out of shot, (multiple objects)++, (many objects)++, not centered, duplication, repetition, monochromatic, badly drawn, (detailed background)+++"
  height: 768
  width: 512
  inference_steps: 30
  guidance_scale: 5.0
  eta: 1.0
  save_dir: './test_results/'
corridor:
  column_mask: './assets/controlnet_masks/column_tile_mask.png'
  wall_mask: './assets/controlnet_masks/column_inpaint_mask.png'
  height: 512
  width: 768
  column_prompt: "ddstyle, a (side view)++ of a (column)++, ceiling, and floor, of {room_a_name} and {room_b_name}, best quality"
  wall_prompt: "ddstyle, a (wall-painting)++ merging {room_a_name} and {room_b_name}, ceiling and floor, best quality"
  door_prompt: "ddstyle, an (open door)++ to a '({room_name})++', best quality, (no people)+"
  negative_prompt: "top-down, (logo)++, (creature)++, (people)++, (animal)++, (face)++, ugly, badly drawn, worst quality, frame, glare, solar flare, text, monochromatic, duplication, repetition"
  inference_steps: 20
  guidance_scale: 5.0
  eta: 1.0
  save_dir: './test_results/'
sd_model:
  ambient_lora: 'DarkestDungeonV2.safetensors'
  entity_lora: 'NecroSketcherAlpha.safetensors'
  vae: 'vaeFtMse840000EmaPruned_vae.safetensors'
  stable_diffusion: 'aZovyaRPGArtistTools_v4.safetensors'
#  stable_diffusion: 'runwayml-v1-5-pruned-emaonly.safetensors'
  controlnet_mlsd: 'lllyasviel/control_v11p_sd15_mlsd'
  controlnet_inpaint: 'lllyasviel/control_v11p_sd15_inpaint'
  controlnet_softedge: 'lllyasviel/control_v11p_sd15_softedge'
  cache_dir: './models'
  disable_progress_bar: true