rng_seed: -1
temp_dir: './test_results'
levels_dir: './my_levels'
scenarios_dir: './my_scenarios'
tmp_level: 'temp.bin'
start_mode: 'llm'
llm_mode: 'freyr'
theme: 'dark'
can_switch_mode: True
server_ip: '10.60.19.36'
server_port: 8080
username: 'gallorob'
icons:
  bleed: './assets/icons/bleed_icon.png'
  heal: './assets/icons/heal_icon.png'
  stun: './assets/icons/stun_icon.png'
  scare: './assets/icons/scare_icon.png'
dungeon:
  max_enemies_per_encounter: 4
  max_traps_per_encounter: 1
  max_treasures_per_encounter: 1
  max_num_attacks: 4
  corridor_min_length: 2
  corridor_max_length: 4
  min_hp: 1.0
  max_hp: 20.0
  min_base_dmg: 0.0
  max_base_dmg: 5.0
  min_dodge: 0.01
  max_dodge: 0.99
  min_prot: 0.01
  max_prot: 0.99
  min_spd: 0.1
  max_spd: 1.0
ui:
  entity_scale: 0.35
  modifier_scale: 0.1
  minimap_room_scale: 0.4
  minimap_corridor_scale: 0.2
  selected_color: '#ffbf00'
  unselected_color: '#b38600'
llm:
  chat:
    model: 'gemma2:latest'
    prompt: './assets/prompts/chat_system_prompt'
    temperature: 0.6
    top_p: 0.2
    top_k: 10
  summary: 
    model: 'gemma2:latest'
    prompt: './assets/prompts/summary_system_prompt'
    temperature: 0.6
    top_p: 0.2
    top_k: 10
  intent: 
    model: 'gemma2:latest'
    prompt: './assets/prompts/intent_system_prompt'
    temperature: 0.01
    top_p: 0.2
    top_k: 10
  params: 
    model: 'gemma2:latest'
    prompt: './assets/prompts/params_system_prompt'
    err_msg: './assets/prompts/params_err_feedback'
    temperature: 0.2
    top_p: 0.2
    top_k: 10
  tools: 
    model: 'llama3.1:latest'
    prompt: './assets/prompts/tools_system_prompt'
    temperature: 0.4
    top_p: 0.2
    top_k: 10
  proactive:
    msg: './assets/prompts/proactive_msg'
    chance: 0.5
room:
  height: 512
  width: 1024
  save_dir: './test_results/'
entity:
  height: 768
  width: 512
  save_dir: './test_results/'
corridor:
  height: 512
  width: 768
  save_dir: './test_results/'